backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "public/img/uploads"
public_folder: "/img/uploads"
collections: 
 - name: "portfolio"
   label: "Portfolio"
   folder: "src/_portfolio"
   create: true
   fields:
    - {label: "Title", name: "title", widget: "string", tagname: "h2"}
    - {label: "Description", name: "description", widget: "string"}
    - {label: "Image", name: "image", widget: "image"}
    - {label: "Icon", name: "icon", widget: "image"}
    - {label: "Tags", name: "tags", widget: "list", default: ['portfolio']}
 - name: "latest-work"
   label: "Latest Work"
   folder: "src/_work"
   create: true
   fields:
    - {label: "Title", name: "title", widget: "string", tagname: "h2"}
    - {label: "Hero Image", name: "heroImage", widget: "image"}
    - {label: "Icon", name: "icon", widget: "image"}
    - {label: "Social Media", name: "social-media", widget: "select", options: ['Facebook', 'Instagram', 'Linkedin', 'TikTok']}
    - {label: "Slogan", name: "slogan", widget: "string"}
    - {label: "Tags", name: "tags", widget: "list", default: ['work']}
 - name: "reviews"
   label: "Reviews"
   folder: "src/_reviews"
   create: true
   fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Profile Picture", name: "profile-pic", widget: "image"}
    - {label: "Date", name: "date", widget: "date", format: "DD.MM.YYYY"}
    - {label: "Tags", name: "tags", widget: "list", default: ['review']}
    - {label: "Text", name: "text", widget: "markdown"}