backend:
  name: git-gateway
  branch: main
media_folder: "public/img/uploads"
public_folder: "/img/uploads"
collections: 
 - name: "portfolio"
   label: "Portfolio"
   folder: "_portfolio"
   create: true
   fields:
    - {label: "Title", name: "title", widget: "string", tagname: "h2"}
    - {label: "Description", name: "description", widget: "string"}
    - {label: "Image", name: "image", widget: "image"}
  - name: "latest-work"
   label: "Latest Work"
   folder: "_work"
   create: true
   fields:
    - {label: "Hero Image", name: "hero-image", widget: "image"}
    - {label: "Social Media", name: "social-media", widget: "select"}
    - {label: "Slogan", name: "slogan", widget: "string"}
    - {label: "Colors", name: "colors", widget: "list", default: ['#fff', "#111", "#ababab"]}