backend:
  name: git-gateway
  branch: main
media_folder: "public/img/uploads"
public_folder: "/img/uploads"
collections: 
 - name: "portfolio"
   label: "Portfolio"
   folder: "_portfolio"
   create: true
   fields:
    - {label: "Title", name: "title", widget: "string", tagname: "h1"}
    - {label: "Description", name: "description", widget: "string"}
    - {label: "Image", name: "image", widget: "image"}